version: '3.9'
services:
  users-db:
    image: postgres
    container_name: users-db
    environment:
      POSTGRES_DB: USERS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - users_db_data:/var/lib/postgresql/data
      - ./dumps/accounts_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

  users-adminer:
    image: adminer
    container_name: users-adminer
    environment:
      ADMINER_DEFAULT_SERVER: users-db
    ports:
      - "8180:8080"
    depends_on:
      - users-db

  users-service:
    build:
      context: ./accounts
    container_name: users-service
    environment:
      DATABASE_URL: postgres://postgres:123@users-db:5431/USERS
    ports:
      - "8081:8081"
    depends_on:
      - users-db




  hospitals-db:
    image: postgres
    container_name: hospitals-db
    environment:
      POSTGRES_DB: HOSPITALS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - hospitals_db_data:/var/lib/postgresql/data
      - ./dumps/hospitals_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  hospitals-adminer:
    image: adminer
    container_name: hospitals-adminer
    environment:
      ADMINER_DEFAULT_SERVER: hospitals-db
    ports:
      - "8182:8080"
    depends_on:
      - hospitals-db

  hospitals-service:
    build:
      context: ./hospitals
    container_name: hospitals-service
    environment:
      DATABASE_URL: postgres://postgres:123@hospitals-db:5432/HOSPITALS
    ports:
      - "8082:8082"
    depends_on:
      - hospitals-db




  schedules-db:
    image: postgres
    container_name: schedules-db
    environment:
      POSTGRES_DB: SCHEDULE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - schedules_db_data:/var/lib/postgresql/data
      - ./dumps/schedules_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  schedules-adminer:
    image: adminer
    container_name: schedules-adminer
    environment:
      ADMINER_DEFAULT_SERVER: schedules-db
    ports:
      - "8183:8080"
    depends_on:
      - schedules-db

  schedules-service:
    build:
      context: ./schedule
    container_name: schedules-service
    environment:
      DATABASE_URL: postgres://postgres:123@schedules-db:5433/SCHEDULE
    ports:
      - "8083:8083"
    depends_on:
      - schedules-db





  documents-db:
    image: postgres
    container_name: documents-db
    environment:
      POSTGRES_DB: DOCUMENTS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - documents_db_data:/var/lib/postgresql/data
      - ./dumps/documents_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  documents-adminer:
    image: adminer
    container_name: documents-adminer
    environment:
      ADMINER_DEFAULT_SERVER: documents-db
    ports:
      - "8184:8080"
    depends_on:
      - documents-db

  documents-service:
    build:
      context: ./documents
    container_name: documents-service
    environment:
      DATABASE_URL: postgres://postgres:123@documents-db:5434/DOCUMENTS
    ports:
      - "8084:8000"
    depends_on:
      - documents-db

volumes:
  users_db_data:
  hospitals_db_data:
  schedules_db_data:
  documents_db_data:
