version: '3.9'
services:
  users-db:
    image: postgres
    container_name: users-db
    environment:
      POSTGRES_DB: USERS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - users_db_data:/var/lib/postgresql/data
      - ./dumps/accounts_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  users-adminer:
    image: adminer
    container_name: users-adminer
    environment:
      ADMINER_DEFAULT_SERVER: users-db
    ports:
      - "8180:8080"
    depends_on:
      - users-db

  users-service:
    build:
      context: ./accounts
    container_name: users-service
    environment:
      DATABASE_URL: postgres://postgres:123@users-db:5432/USERS
    ports:
      - "8081:8081"
    depends_on:
      - users-db

volumes:
  users_db_data:
